In [2]:
import numpy as np

In [14]:
miles_list = [280,300,360,240]
gallons_list = [7.1, 8.2, 10.1, 6.8]

trip_info = np.array([miles_list, gallons_list])
trip_info

array([[280. , 300. , 360. , 240. ],
       [  7.1,   8.2,  10.1,   6.8]])

In [8]:
trip_info[0]

array([280., 300., 360., 240.])

In [9]:
trip_info[0][0]

280.0

In [10]:
trip_info[0,0]

280.0

In [11]:
trip_info[0,0:2]

array([280., 300.])

In [13]:
mpg = trip_info[0] / trip_info[1]
mpg

array([39.43661972, 36.58536585, 35.64356436, 35.29411765])

In [17]:
trip_info = np.append(trip_info, [mpg], axis=0)
trip_info

array([[280.        , 300.        , 360.        , 240.        ],
       [  7.1       ,   8.2       ,  10.1       ,   6.8       ],
       [ 39.43661972,  36.58536585,  35.64356436,  35.29411765],
       [ 39.43661972,  36.58536585,  35.64356436,  35.29411765],
       [ 39.43661972,  36.58536585,  35.64356436,  35.29411765]])