In [1]:
import numpy as np

In [2]:
numbers = np.arange(9)
numbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
numbers = np.arange(9,15)
numbers

array([ 9, 10, 11, 12, 13, 14])

In [4]:
numbers = np.arange(6,32,5)
numbers

array([ 6, 11, 16, 21, 26, 31])

In [6]:
numbers = np.arange(6,32,0.5)
numbers

array([ 6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. ,
       11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5,
       17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5, 22. ,
       22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5,
       28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5])