In [1]:
import numpy as np

<h1 style="color:red;">np.arange()</h1>

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
y = np.arange(4,9)
y

array([4, 5, 6, 7, 8])

In [7]:
z = np.arange(3,23,4)
z

array([ 3,  7, 11, 15, 19])

<h1 style="color:red;">np.linspace()</h1>

In [13]:
x = np.linspace(0,15,10)   # 3. argüman, almak istenilen eleman sayısı, varsayılan 50 elemandır.
x

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        , 11.66666667, 13.33333333, 15.        ])

In [10]:
x = np.linspace(0,15,10, endpoint=False)   # son eleman alınmıyor
x

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5])

<h1 style="color:red;">np.reshape() </h1>

In [18]:
x = np.arange(20)
print(x)

y = np.reshape(x, (4,5))
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [19]:
x = np.arange(32)
print(x)

y = np.reshape(x, (2,4,4))
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]


In [22]:
x = np.linspace(0,19,20)
print(x)

y = np.reshape(x, (2,10))
print(y)

z = x.reshape(2,10)
print(z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]


<h1 style="color:red;">np.random.random() -> [0,1)</h1>

In [23]:
x = np.random.random((2,3))
x

array([[0.26931808, 0.67109337, 0.62336852],
       [0.70326288, 0.45543504, 0.04368709]])

<h1 style="color:red;">np.random.randint()</h1>

In [24]:
x = np.random.randint(3,12, size=(3,2))
x

array([[ 6,  4],
       [ 3,  7],
       [10,  9]])