In [1]:
import numpy as np

<h1 style="color:red;">np.intersect1d</h1>

In [2]:
x = np.array([2,5,3,6,9])
y = np.array([6,1,8,7,3])

print(np.intersect1d(x,y))

[3 6]


<h1 style="color:red;">np.setdiff1d</h1>

In [4]:
print(np.setdiff1d(x,y))
print(np.setdiff1d(y,x))

[2 5 9]
[1 7 8]


<h1 style="color:red;">np.union1d</h1>

In [6]:
print(np.union1d(x,y))

[1 2 3 5 6 7 8 9]


<h1 style="color:red;">np.in1d</h1>

In [7]:
print(np.in1d(x,y))

[False False  True  True False]


<h1 style="color:red;">np.unique</h1>

In [10]:
x = np.array([2,5,3,6,9,3,6,5,0])
print(np.unique(x))

[0 2 3 5 6 9]


<h1 style="color:red;">np.sort</h1>

In [17]:
x = np.random.randint(1,10,size=(10,))
print(x)
print(np.sort(x))  # orginal sıralanmaz
print(x)
print("=======================")
y = np.random.randint(1,10,size=(10,))
print(y)
y.sort()    # method olarak olduğunda orginali de sıralar
print(y)

[6 3 7 7 3 1 6 3 3 8]
[1 3 3 3 3 6 6 7 7 8]
[6 3 7 7 3 1 6 3 3 8]
[2 1 9 9 1 5 6 1 8 7]
[1 1 1 2 5 6 7 8 9 9]


In [20]:
x = np.random.randint(1,10, size=(5,5))
print(x)
print("=======================")
print(np.sort(x, axis=0))   # axis=0 sürunlara göre 
print("=======================")
print(np.sort(x, axis=1))   # axis=0 satırlara göre 

[[7 9 3 6 1]
 [6 6 4 7 6]
 [9 1 3 1 1]
 [8 6 9 5 2]
 [7 5 3 3 1]]
[[6 1 3 1 1]
 [7 5 3 3 1]
 [7 6 3 5 1]
 [8 6 4 6 2]
 [9 9 9 7 6]]
[[1 3 6 7 9]
 [4 6 6 6 7]
 [1 1 1 3 9]
 [2 5 6 8 9]
 [1 3 3 5 7]]
