In [1]:
import numpy as np

<h1 style="color:red;">ndarray[start:end], ndarray[start:], ndarray[:end]</h1>

In [7]:
x = np.arange(10)
print(x)
print(x[2:6])
print(x[4:])
print(x[:7])

print(x[:-1])
print(x[-4:-2])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8]
[6 7]


In [8]:
x = np.arange(25).reshape(5,5)
print(x)
print('================')
y = x[0:3,1:4]        # 0,1,2 satırlarını al, sonra 1,2,3 sütunlarını al
print(y)
print('================')
z = x[2:]             # 2 satırdan sona kadar al, sütunda bir durum yok
print(z)
print('================')
t = x[::]             # satırların ve sütunların tamamını al
print(t)
print('================')
v = x[:,3:]           # satırların tamamı ve sütunların 3 ten itibaren tamamı
print(v)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


<h1 style="color:red;">copy</h1>

In [11]:
x = np.arange(9).reshape(3,3)
print(x)
print('================')
y = x[1:2, 0:2]
print(y)
print('================')
y[0,0] = 100
print(y)              # x de değişiyor
print('================')
print(x)
print('================')
print(np.shares_memory(x,y))   # x ve y aynı memory kullanıyor

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4]]
[[100   4]]
[[  0   1   2]
 [100   4   5]
 [  6   7   8]]
True


In [15]:
x = np.arange(16).reshape(4,4)
print(x)
print('================')
y = np.copy(x[0:3, 1:3])
print(y)
print('================')
print(np.shares_memory(x,y))   # x ve y aynı memory kullanmıyorlar
print('================')
y[0,0] = 100
print(y)              # x de değişiyor
print('================')
print(x)
print('================')
z = x[1:2, 1:2].copy()
print(z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
False
[[100   2]
 [  5   6]
 [  9  10]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[5]]
