In [1]:
import numpy as np

In [5]:
x = np.array([1,2,3], dtype=np.int)   # dışarıdan veritiplerinin belirlenmesi
print(x)
print(x.dtype)

[1 2 3]
int32


In [6]:
y = np.array([1,2,3], dtype=np.float)
print(y)
print(y.dtype)

[1. 2. 3.]
float64


In [7]:
z = np.array([1,2,3], dtype=np.complex)
print(z)
print(z.dtype)

[1.+0.j 2.+0.j 3.+0.j]
complex128


In [11]:
x = x.astype(np.float)
x

array([1., 2., 3.])

In [12]:
x = np.array(x, dtype=np.complex)   # varolan ndarray in veritipinin değiştirilmesi
print(x)
print(x.dtype)

[1.+0.j 2.+0.j 3.+0.j]
complex128


In [13]:
x1 = np.array([1,2,3], dtype=np.int)
x2 = np.array([5.2, 2.8, 4.9], dtype=np.float)

print(x1 + x2)
print((x1 + x2).dtype)

[6.2 4.8 7.9]
float64


In [16]:
x = np.sqrt(np.array([-1,9,4], dtype=np.float))
print(x)
print(x.dtype)

[nan  3.  2.]
float64


C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


In [18]:
x = np.sqrt(np.array([-1,9,4], dtype=np.complex))
print(x)
print(x.dtype)
print(x.real)
print(x.imag)

[0.+1.j 3.+0.j 2.+0.j]
complex128
[0. 3. 2.]
[1. 0. 0.]


In [19]:
x = np.array([5,9,3.2,16])
np.save('ndarray_1', x)      # save

In [21]:
y = np.load('ndarray_1.npy')      # load
y

array([ 5. ,  9. ,  3.2, 16. ])