In [1]:
import numpy as np

In [4]:
x = np.linspace(1,21,11)
print(x)
y = np.array([2,4,7])
print(y)
print('===========================')
print(x[y])      # y ndarray e göre x deki elemanlar listelenir

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]
[2 4 7]
[ 5.  9. 15.]


<h1 style="color:red;">Fancy indexing</h1>

In [8]:
x = np.arange(25).reshape(5,5)
print(x)
y = np.array([1,2])
print(y)
print('===========================')
print(x[y,:])
print('===========================')
print(x[:,y])
print('===========================')
z = x[y,:]
print(z)
z[0,0] = 100    # x deki eleman değişmedi (başka bir ndarray ile yapıldığından)
print(z)
print(x)
print('===========================')
print(np.shares_memory(x,z))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[1 2]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[100   6   7   8   9]
 [ 10  11  12  13  14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
False


<h1 style="color:red;">Boolean indexing</h1>

In [10]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
print(x[(x % 2 == 0)])

[0 2 4 6 8]


In [12]:
z = x[(x % 2 == 0)]
print(np.shares_memory(x,z))

False


In [20]:
x = np.random.randint(10, size=10)
y = np.random.randint(10, size=10)

print(x)
print(y)
z = x>y
print(z)
print(type(z))
print((z).dtype)
print(x[z])
print(np.all(x>y))
print(np.any(x>y))

[2 4 6 8 1 5 3 6 4 3]
[4 2 0 3 3 9 9 8 4 2]
[False  True  True  True False False False False False  True]
<class 'numpy.ndarray'>
bool
[4 6 8 3]
False
True


In [22]:
x = np.linspace(1,21,11)
print(x)
mask = (x % 3 == 0)
print(mask)
print(type(mask))
print(x[mask])     # koşula uyan elemanları gösterir
x[mask] = -3     # koşula uyan elemanları -3 ile değiştirilir
print(x)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]
[False  True False False  True False False  True False False  True]
<class 'numpy.ndarray'>
[ 3.  9. 15. 21.]
[ 1. -3.  5.  7. -3. 11. 13. -3. 17. 19. -3.]
