In [1]:
import numpy as np

In [2]:
x = np.random.randint(1,10, size=(8,))
x

array([1, 1, 9, 8, 5, 7, 6, 1])

In [4]:
print(x.mean())
print(np.median(x))
print(x.std())

4.75
5.5
3.112474899497183


In [5]:
y = np.random.randint(1,10, size=(4,3))
y

array([[5, 4, 7],
       [4, 6, 1],
       [6, 8, 6],
       [7, 1, 3]])

In [6]:
print(y.mean(axis=0))
print(np.median(y, axis=1))
print(x.std(axis=0))

[5.5  4.75 4.25]
[5. 4. 6. 3.]
3.112474899497183


In [7]:
x = np.random.randint(1,10, size=(3,2))
print(x)
y = np.random.randint(1,10, size=(3,2))
print(y)
print(x + y)

[[9 7]
 [4 6]
 [4 1]]
[[3 1]
 [1 9]
 [9 2]]
[[12  8]
 [ 5 15]
 [13  3]]


<h1 style="color:red;">Broadcasting</h1>

In [10]:
x = np.random.randint(1,10, size=(1,))
print(x)
print('======================')
y = np.random.randint(1,10, size=(3,2))
print(y)
print('======================')
print(x + y)

[9]
[[5 8]
 [6 8]
 [9 7]]
[[14 17]
 [15 17]
 [18 16]]


In [11]:
x = np.random.randint(1,10, size=(2,))
print(x)
print('======================')
y = np.random.randint(1,10, size=(3,2))
print(y)
print('======================')
print(x + y)

[5 3]
[[6 9]
 [7 8]
 [7 4]]
[[11 12]
 [12 11]
 [12  7]]


In [12]:
x = np.random.randint(1,10, size=(3,))
print(x)
print('======================')
y = np.random.randint(1,10, size=(3,2))
print(y)
print('======================')
print(x + y)

[8 9 8]
[[1 1]
 [4 1]
 [9 4]]


ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [14]:
x = np.random.randint(1,10, size=(1,3))
print(x)
print('======================')
y = np.random.randint(1,10, size=(3,1))
print(y)
print('======================')
print(x + y)

[[8 8 6]]
[[1]
 [8]
 [5]]
[[ 9  9  7]
 [16 16 14]
 [13 13 11]]
