In [1]:
import numpy as np

element - wise, array - wise

In [2]:
x = np.random.randint(1,10, size=(5,))
print(x)
y = np.random.randint(1,10, size=(5,))
print(y)

[9 6 7 7 7]
[8 2 8 7 5]


In [3]:
print(x + y)
print(np.add(x,y))

[17  8 15 14 12]
[17  8 15 14 12]


In [6]:
print(x - y)
print(np.subtract(x,y))

[ 1  4 -1  0  2]
[ 1  4 -1  0  2]


In [4]:
print(x * y)
print(np.multiply(x,y))

[72 12 56 49 35]
[72 12 56 49 35]


In [5]:
print(x / y)
print(np.divide(x,y))

[1.125 3.    0.875 1.    1.4  ]
[1.125 3.    0.875 1.    1.4  ]


In [7]:
print(x + 3)
print(x - 3)
print(x * 3)
print(x / 3)

[12  9 10 10 10]
[6 3 4 4 4]
[27 18 21 21 21]
[3.         2.         2.33333333 2.33333333 2.33333333]


In [9]:
print(x == y)
print(np.array_equal(x,y))

[False False False  True False]
False


In [13]:
print(np.sqrt(x))
print(np.power(x,3))
print(np.exp(x))

[3.         2.44948974 2.64575131 2.64575131 2.64575131]
[729 216 343 343 343]
[8103.08392758  403.42879349 1096.63315843 1096.63315843 1096.63315843]


In [16]:
x = np.random.randint(1,10, size=(9,)).reshape(3,3)
print(x)
print(np.sum(x))
print(x.sum(axis=0))
print(x.sum(axis=1))
print(x.min())
print(x.max())
print(x.argmin())   # en küçük elemanın index sırası
print(x.argmax())   # en büyük elemanın index sırası

[[6 9 1]
 [5 6 3]
 [3 3 4]]
40
[14 18  8]
[16 14 10]
1
9
2
1
