In [1]:
import numpy as np

1) Sinemaya giriş ücreti öğrenciler için 5 TL, olmayanlar için 10 TL dir. 100 kişi için 700 TL toplandığına göre öğrenci sayısı kaçtır. (x1 + x2 = 100, 5x1 + 10x2 = 700)

In [4]:
A = np.array([[1,1], [5,10]])    # katsayılar yazılır
print (A)
print('=================')       # katsayılara ait sonuçlar
B = np.array([100,700])
print(B)
print('=================')
x = np.linalg.solve(A,B)         # X1 ve X2
print(x)

[[ 1  1]
 [ 5 10]]
[100 700]
[60. 40.]


2) Tek boyutlu ve çift boyutlu ND Arrayler için skaler çarpım örnekleri gösteriniz

In [6]:
x = np.random.randint(1,5,6)
print(x)
y = np.random.randint(1,5,6)
print(y)
print('=================')
print(np.dot(x,y))      # (3*3 + 3*2 + 3*4 ... = 45)

[2 4 2 4 2 4]
[3 1 3 4 4 3]
52


In [8]:
x = np.random.randint(1,5,6).reshape(3,2)
print(x)
y = np.random.randint(1,5,6).reshape(2,3)
print(y)
print('=================')
print(np.dot(x,y))      # (2*1 + 3*3 = 11) , (2*3 + 3*3 = 15) , (2*2 + 3*2 = 10) .....)

[[4 2]
 [1 2]
 [2 4]]
[[3 1 1]
 [4 1 3]]
[[20  6 10]
 [11  3  7]
 [22  6 14]]
