In [1]:
import numpy as np

In [8]:
x = np.arange(5)
print(x)
print(x[2])
print(x[-1])

x[2] = 200
print(x)

[0 1 2 3 4]
2
4
[  0   1 200   3   4]


In [13]:
x = np.arange(12).reshape(3,4)
print(x)
print(x[0,2])

x[0,0] = 100
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


<h1 style="color:red;">delete</h1>

In [15]:
x = np.arange(6)
print(x)

y = np.delete(x, [0,1])
print(y)

[0 1 2 3 4 5]
[2 3 4 5]


<h1 style="color:red;"> np.delete -> axis=0 row, axis=1 column </h1>

In [28]:
x = np.arange(16).reshape(4,4)
print(x)
print('==================')
y = np.delete(x, 1, axis=0)
print(y)
print('==================')
z = np.delete(x, [0,2], axis=1)
print(z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


<h1 style="color:red;"> np.append </h1>

In [34]:
x = np.arange(5)
print(x)

x = np.append(x, 100)
print(x)

x = np.append(x, [200,300])
print(x)

[0 1 2 3 4]
[  0   1   2   3   4 100]
[  0   1   2   3   4 100 200 300]


In [42]:
x = np.arange(9).reshape(3,3)
print(x)
print('==================')
x = np.append(x, [[100,200,300]], axis=0)
print(x)
print('==================')
x = np.append(x, [[10],[20],[30],[40]], axis=1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[  0   1   2]
 [  3   4   5]
 [  6   7   8]
 [100 200 300]]
[[  0   1   2  10]
 [  3   4   5  20]
 [  6   7   8  30]
 [100 200 300  40]]


<h1 style="color:red;"> np.insert --> (ndarray, index, element, axis)</h1>

In [43]:
x = np.arange(5)
print(x)

x = np.insert(x, 1, 10)
print(x)

x = np.insert(x, 0, [20,30])
print(x)

[0 1 2 3 4]
[ 0 10  1  2  3  4]
[20 30  0 10  1  2  3  4]


In [46]:
x = np.arange(9).reshape(3,3)
print(x)
print('==================')
x = np.insert(x, 1, [[100,200,300]], axis=0)
print(x)
print('==================')
x = np.insert(x, 0, [10,20,30,40], axis=1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[  0   1   2]
 [100 200 300]
 [  3   4   5]
 [  6   7   8]]
[[ 10   0   1   2]
 [ 20 100 200 300]
 [ 30   3   4   5]
 [ 40   6   7   8]]


<h1 style="color:red;"> np.stack</h1>

In [52]:
x = np.arange(3)
print(x)
print('==================')
y = np.arange(3,12).reshape(3,3)
print(y)
print('==================')
z = np.vstack((x,y))      # vstack = vertical stack = dikey iliştirme
print(z)
print('==================')
y = y.reshape((9,))
t = np.hstack((x,y))      # hstack = horizontal stack = yatay iliştirme
print(t)

[0 1 2]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
