In [1]:
import numpy as np

In [6]:
x1 = np.zeros(4)
print(x1)
print(x1.dtype)

[0. 0. 0. 0.]
float64


In [7]:
y1 = np.ones(4)
print(y1)
print(y1.dtype)

[1. 1. 1. 1.]
float64


In [8]:
x2 = np.zeros((2,3,4), dtype=np.int)
print(x2)
print(x1.dtype)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
float64


In [10]:
y2 = np.ones((3,2))
print(y2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
x = np.full((2,3),10)
print(x)
print(x.dtype)

[[10 10 10]
 [10 10 10]]
int32


<h1 style="color:red;">np.full</h1>

In [14]:
x = np.full((2,3),10.0)
print(x)
print(x.dtype)

[[10. 10. 10.]
 [10. 10. 10.]]
float64


In [15]:
y = 10.0 * np.ones((2,3))
z = 10.0 + np.zeros((2,3))
print(y)
print(z)

[[10. 10. 10.]
 [10. 10. 10.]]
[[10. 10. 10.]
 [10. 10. 10.]]


<h1 style="color:red;">np.empty (değerler rastgele verilir)</h1>

In [25]:
x = np.empty((2,3))
x

array([[10., 10., 10.],
       [10., 10., 10.]])

<h1 style="color:red;">np.fill (np.empty -> boş olan verileri doldurur)</h1>

In [27]:
x.fill(3)
x

array([[3., 3., 3.],
       [3., 3., 3.]])

<h1 style="color:red;">np.eye (birim matris) = np.identity</h1>

In [29]:
x = np.eye(4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
y = np.eye(5,4)
y

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [32]:
x = np.eye(6)
y = np.eye(6, k=1)
z = np.eye(6, k=-2)
print(x)
print(y)
print(z)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


<h1 style="color:red;">np.diag</h1>

In [34]:
x = np.diag([4,7,11,3])
x

array([[ 4,  0,  0,  0],
       [ 0,  7,  0,  0],
       [ 0,  0, 11,  0],
       [ 0,  0,  0,  3]])