In [1]:
import numpy as np

In [4]:
random = np.random.rand(5,3)
#np.random.shuffle(random[:,0])
random

array([[0.80759292, 0.64178547, 0.12310785],
       [0.95821196, 0.69756365, 0.69662325],
       [0.34048172, 0.41716776, 0.89720927],
       [0.95721022, 0.87188431, 0.5912698 ],
       [0.05273979, 0.0382836 , 0.58068224]])

In [5]:
np.random.shuffle(random[:,0])
random

array([[0.80759292, 0.64178547, 0.12310785],
       [0.95821196, 0.69756365, 0.69662325],
       [0.95721022, 0.41716776, 0.89720927],
       [0.05273979, 0.87188431, 0.5912698 ],
       [0.34048172, 0.0382836 , 0.58068224]])

In [6]:
np.random.shuffle(random)
random

array([[0.80759292, 0.64178547, 0.12310785],
       [0.95821196, 0.69756365, 0.69662325],
       [0.34048172, 0.0382836 , 0.58068224],
       [0.05273979, 0.87188431, 0.5912698 ],
       [0.95721022, 0.41716776, 0.89720927]])

In [9]:
np.random.permutation(random[:,0])
random

array([[0.80759292, 0.64178547, 0.12310785],
       [0.95821196, 0.69756365, 0.69662325],
       [0.34048172, 0.0382836 , 0.58068224],
       [0.05273979, 0.87188431, 0.5912698 ],
       [0.95721022, 0.41716776, 0.89720927]])

In [10]:
np.random.normal(50, 15, (3, 4))

array([[70.438739  , 39.93348936, 41.69169265, 64.3831843 ],
       [37.45391071, 45.89528222, 63.19698122, 41.76497811],
       [55.72533995, 38.16822628, 36.94576561, 33.56670309]])